engine:
  gpu_id: 0
  nx: false  # if build engine on nx, must set false while gpu_id is not 0
  mode: 16  # 32/16/8 mean fp32/fp16/int8
  workspace: 2048  # MB
  onnx_file: "../models/face_3d.onnx"
  engine_file: "../models/face_3d.bin"
  bchw: [1, 3, 112, 112]
params:
  num_classes: 1000
  means: [127.5, 127.5, 127.5]
  stds: [128, 128, 128]
  image_format: 3  # 0: rgb, 1: rgb255, 2: bgr, 3: bgr255
misc:
  show_time: true
inputs:  # for main.cpp to test the algorithm
  video_path: ""
  img_path: "../data/sample_data/coco_1.jpg"
  width: 96
  height: 96
