engine:
  gpu_id: 0
  nx: false  # if build engine on nx, must set false while gpu_id is not 0
  mode: 16  # 32/16/8 mean fp32/fp16/int8
  workspace: 2048  # MB
  onnx_file: "../models/fcos_DLA-34c-FPN64@3T5-ST2-SYNCBN128_4x_ms512_fisheye_ctr_BCHW_1x3x512x512.onnx"
  engine_file: "../models/fcos_DLA-34c-FPN64@3T5-ST2-SYNCBN128_4x_ms512_fisheye_ctr_BCHW_1x3x512x512_fp16.bin"
  bchw: [1, 3, 512, 512]
params:
  num_classes: 1
  det_thresh: 0.6
  nms_thresh: 0.6
  means: [103.52, 116.28, 123.675]
  stds: [57.375,57.12,58.395]
  output_index: [1, 2, 3, 4, 5, 6, 7, 8, 9]  # output binding idx
  image_format: 3  # 0: rgb, 1: rgb255, 2: bgr, 3: bgr255
misc:
  show_time: true
sub_tasks:  # if you don't need run sub task, remove all the config below
  tasks: []  # only cls for now
  cls:
    engine:
      gpu_id: 0
      nx: false  # if build engine on nx, must set false while gpu_id is not 0
      mode: 16  # 32/16/8 mean fp32/fp16/int8
      workspace: 2048  # MB
      onnx_file: "../models/mobilenet_v3_small_minimal_1x_BCHW_2x3x56x28.onnx"
      engine_file: "../models/mobilenet_v3_small_minimal_1x_BCHW_2x3x56x28_fp16.bin"
      bchw: [2, 1, 56, 28]
    params:
      num_thresh: 0.6
      num_classes: 1000
    misc:
      show_time: true
inputs:  # for main.cpp to test the algorithm
  video_path: ""
  img_path: "../data/sample_data/coco_1.jpg"
  width: 512
  height: 512