engine:
  gpu_id: 0
  nx: false  # if build engine on nx, must set false while gpu_id is not 0
  mode: 16  # 32/16/8 mean fp32/fp16/int8
  workspace: 2048  # MB
  onnx_file: "../models/pspnet_8.onnx"
  engine_file: "../models/pspnet_8.bin"
  bchw: [1, 3, 1024, 1024]
params:
  num_classes: 8
  means: [0, 0, 0]
  stds: [1, 1, 1]
  image_format: 3  # 0: rgb, 1: rgb255, 2: bgr, 3: bgr255
  output_index: [1]  # output binding idx
misc:
  show_time: true
inputs:  # for main.cpp to test the algorithm
  video_path: ""
  img_path: "../data/sample_data/coco_1.jpg"
  width: 1024
  height: 1024
