engine:
  gpu_id: 0
  nx: false  # if build engine on nx, must set false while gpu_id is not 0
  mode: 16  # 32/16/8 mean fp32/fp16/int8
  workspace: 2048  # MB
  onnx_file: "../models/fcn_r50_1x3x512x512_o21.onnx"
  engine_file: "../models/fcn_r50_1x3x512x512_o21.bin"
  bchw: [1, 3, 512, 512]
params:
  num_classes: 21
  means: [0, 0, 0]
  stds: [1, 1, 1]
  color_mode: "bgr"
  output_idx: [1]  # output binding idx
misc:
  show_time: true
inputs:  # for main.cpp to test the algorithm
  video_path: ""
  img_path: "../data/sample_data/coco_1.jpg"
  width: 512
  height: 512
